### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by mmcnulty20** [chrisweeting/Dwel#1]
- [x] Add logging out as part of auth
- [x] Add the splash page as part of auth
- [x] More details of what information about the listing is displayed 
- [x] Can existing listings be deleted by ANY authorized users?
- [x] Move Map to right after listings (ahead of saves)
- [x] What do users need to be logged in for? What can they access while logged out.
- [x] I only see saves, not likes
- [x] Add additional detail (Have 3+ bullet points for each MVP)

**Comment by chrisweeting** [comment]
Thanks for the notes! I think I have everything covered now.
